### ISSUE TITLE
Old donation address was lost

### ISSUE THREAD

**Issue by dulanov** [nem-toolchain/nem-toolchain#127]
Due to #126 we lost our old donation address, my proposal to find a new one:

`nem account vanity --exclude 246 N_____-E_____-M_____-T_____-O_____-O_____-L`

**Comment by dulanov** [comment]
Depends on #112.

**Comment by dulanov** [comment]
Estimate times on my 6 years old i3 notebook:

```
> nem-snapshot account vanity --exclude 246 N_____-E_____-M_____-T_____-O_____-O_____-L
Calculate accounts rate... 14936 accounts/sec
Estimate search times: 323h1m28s (50%), 750h2m24s (80%), 2146h7m45s (99.9%)
```

**Comment by r8d8** [comment]
New address found `NCSY3D-EVBGVX-MEPZWK-TIJWCA-OXL5NE-OLJPHX-LFLD`
