### ISSUE TITLE
Lack of account sub-command to show account's details

### ISSUE THREAD

**Issue by r8d8** [nem-toolchain/nem-toolchain#139]
Required account sub-command to extract public address from given private key - `cat | account info --address-only`, related to #124.

**Comment by r8d8** [comment]
@dulanov, do we need `--public, `--private` flags?

**Comment by dulanov** [comment]
I think `info` sub-command take private key and by default print account pretty details, so we need only options fully similar to `generate` & `vanity` account sub-commans - `--strip`, `--only-address`, `--only-public`.
