### ISSUE TITLE
undefined: sha3.SumKeccak256

### ISSUE THREAD

**Issue by ghost** [nem-toolchain/nem-toolchain#160]
### Description

undefined: sha3.SumKeccak256 in keypair.go

### Steps to reproduce

go get github.com/nem-toolchain/nem-toolchain/cmd/nem

go/src/github.com/nem-toolchain/nem-toolchain/pkg/keypair/keypair.go:59:7: undefined: sha3.SumKeccak256

go/src/github.com/nem-toolchain/nem-toolchain/pkg/keypair/keypair.go:69:6: undefined: sha3.SumKeccak256

### Go version :
 1.9

### OS version : 
10.13.4

**Comment by r8d8** [comment]
@trungkysis, have you installed nem-toolchain throught `go get` ?

**Comment by trungkysis** [comment]
@r8d8 
Yes, i have installed. 
Maybe, golang/x/crypto version is deffierent ?  
I can not find function sha3.SumKeccak256 in golang/x/crypto.

**Comment by r8d8** [comment]
yeap, we having fork.
Try to run `make setup` - dep should provide right dependency

**Comment by trungkysis** [comment]
@r8d8 

It work fine. Thank so much !
